/* Generated By:JavaCC: Do not edit this line. ParserIDBQueryToJavaConstants.java */
package parserIDBQuery;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserIDBQueryToJavaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int marks = 5;
  /** RegularExpression Id. */
  int open = 6;
  /** RegularExpression Id. */
  int end = 7;
  /** RegularExpression Id. */
  int punkt = 8;
  /** RegularExpression Id. */
  int string = 9;
  /** RegularExpression Id. */
  int operators = 10;
  /** RegularExpression Id. */
  int number = 11;
  /** RegularExpression Id. */
  int digit = 12;
  /** RegularExpression Id. */
  int not = 13;
  /** RegularExpression Id. */
  int kindValue = 14;
  /** RegularExpression Id. */
  int nameValue = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\\"\"",
    "\"{\"",
    "\"}\"",
    "\":\"",
    "<string>",
    "<operators>",
    "<number>",
    "<digit>",
    "\"not\"",
    "<kindValue>",
    "<nameValue>",
    "\":-\"",
    "\".\"",
    "\",\"",
    "\"(\"",
    "\")\"",
  };

}
