/* Generated By:JavaCC: Do not edit this line. ParserForGetConstants.java */
package parserGetToDatalog;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserForGetConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int marks = 5;
  /** RegularExpression Id. */
  int open = 6;
  /** RegularExpression Id. */
  int end = 7;
  /** RegularExpression Id. */
  int punkt = 8;
  /** RegularExpression Id. */
  int string = 9;
  /** RegularExpression Id. */
  int number = 10;
  /** RegularExpression Id. */
  int digit = 11;
  /** RegularExpression Id. */
  int get = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\\"\"",
    "\"{\"",
    "\"}\"",
    "\":\"",
    "<string>",
    "<number>",
    "<digit>",
    "\"get\"",
    "\".\\\"id\\\"=\"",
  };

}
