/* Generated By:JavaCC: Do not edit this line. ParserForFunctionsConstants.java */
package parserFunctionsToDatalog;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserForFunctionsConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int add = 5;
  /** RegularExpression Id. */
  int delete = 6;
  /** RegularExpression Id. */
  int copy = 7;
  /** RegularExpression Id. */
  int move = 8;
  /** RegularExpression Id. */
  int string = 9;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"add\"",
    "\"delete\"",
    "\"copy\"",
    "\"move\"",
    "<string>",
    "\".\"",
    "\"=\"",
    "\" to \"",
    "\" where \"",
  };

}
